;;; config.el --- storax-powerline layer config file for Spacemacs.
;;
;; Copyright (c) 2012-2016 Sylvain Benner & Contributors
;;
;; Author: David Zuber <zuber.david@gmx.de>
;; URL: https://github.com/syl20bnr/spacemacs
;;
;; This file is not part of GNU Emacs.
;;
;;; License: GPLv3

;;; Commentary:

;;; Code:

(mode-icons-define-font "github-octicons")
(mode-icons-define-font "font-mfizz")
(mode-icons-define-font "FontAwesome")
(mode-icons-define-font "IcoMoon-Free")
(mode-icons-define-font "icomoon")
(mode-icons-define-font "Sauce Code Pro")

(defcustom mode-icons
  `(
    (" Golden" "golden" xpm) ;; Icon created by Arthur Shlain from Noun Project
    (" Pulls" #xf092 FontAwesome)
    (" Rbow" "rainbow" xpm)
    (" hs" "hs" xpm)
    (" yas" "yas" xpm)
    ("AHK" "autohotkey" xpm)
    ("ARev" #xf021 FontAwesome)
    ("BibTeX" "bibtex" xpm)
    ("C/l" #xf107 font-mfizz)
    ("C?Perl" #xf148 font-mfizz)
    ("CSS" "css" xpm)
    ("C[#]/l" #xf10d font-mfizz)
    ("C[+][+]/l" #xf10c font-mfizz)
    ("Calc\\(ulator\\)?" #xf1ec FontAwesome)
    ("Calendar" #xf073 FontAwesome)
    ("Clojure" #xf10a font-mfizz)
    ("Coffee" "coffee" xpm)
    ("Compilation" "compile" xpm)
    ("Custom" #xf013 FontAwesome)
    ("Debug.*" #xf188 FontAwesome)
    ("Debug.*" #xf188 FontAwesome)
    ("ESS\\[BUGS\\]" #xf188 FontAwesome)
    ("ESS\\[SAS\\]" "sas" xpm)
    ("ESS\\[S\\]" "R" xpm)
    ("Elixir" #xf115 font-mfizz)
    ("Emacs-Lisp" "emacs" xpm)
    ("Erlang" #xf116 font-mfizz)
    ("HTML" "html" xpm)
    ("Haml" "haml" xpm)
    ("Haskell" #xf126 font-mfizz)
    ("Help" #xf059 FontAwesome)
    ("Image[imagemagick]" "svg" xpm)
    ("Inf-Ruby" "infruby" xpm)
    ("Info" #xf05a FontAwesome)
    ("Java/l" #xf12b font-mfizz)
    ("JavaScript" "js" xpm)
    ("Lisp Interaction" "emacs" xpm)
    ("Lisp" "cl" xpm)
    ("Magit" #xf1d2 FontAwesome)
    ("Markdown" #xf0c9 github-octicons)
    ("Narrow" #xf066 FontAwesome)
    ("Octave" "octave" xpm)
    ("Org" "org" xpm)
    ("PHP" "php" xpm)
    ("PHP/l" "php" xpm)
    ("Projectile Rails Server" "rails" xpm)
    ("Python" "python" xpm)
    ("Ruby" "ruby" xpm)
    ("SCSS" "sass" xpm)
    ("Sass" "sass" xpm)
    ("Scala" #xf15b font-mfizz)
    ("Scheme" "scheme" xpm)
    ("Shell-script" "bash" xpm)
    ("Slim" "slim" xpm)
    ("Snippet" "yas" xpm)
    ("Term" "term" xpm)
    ("Text\\'" #xf0f6 FontAwesome)
    ("Web" "html" xpm)
    ("WoMan" #xf05a FontAwesome)
    ("XML" "xml" xpm)
    ("YAML" "yaml" xpm)
    ("YASnippet" "yas" xpm)
    ("Zip-Archive" #xf1c6 FontAwesome)
    ("\\` ?company\\'" #xf1ad FontAwesome)
    ("\\`Go\\'" "go" xpm)
    ("iESS" "R" xpm)
    ("nXML" "xml" xpm)

    ("line_number" #xe0a1 Sauce\ Code\ Pro)
    ("column_number" #xe0a3 Sauce\ Code\ Pro)
    ("lock" #xe0a2 Sauce\ Code\ Pro)
    ("pl_l_flame_b" #xe0c0 Sauce\ Code\ Pro)
    ("pl_l_flame_w" #xe0c1 Sauce\ Code\ Pro)
    ("pl_r_flame_b" #xe0c2 Sauce\ Code\ Pro)
    ("pl_r_flame_w" #xe0c3 Sauce\ Code\ Pro)
    ("pl_l_pixels" #xe0c4 Sauce\ Code\ Pro)
    ("pl_r_pixels" #xe0c5 Sauce\ Code\ Pro)
    ("pl_l_pixels_big" #xe0c6 Sauce\ Code\ Pro)
    ("pl_r_pixels_big" #xe0c7 Sauce\ Code\ Pro)
    ("package" #xf0c4 Sauce\ Code\ Pro)
    ("android" #xe70e Sauce\ Code\ Pro)
    ("angular" #xe753 Sauce\ Code\ Pro)
    ("appcelerator" #xe7ab Sauce\ Code\ Pro)
    ("apple" #xe711 Sauce\ Code\ Pro)
    ("appstore" #xe713 Sauce\ Code\ Pro)
    ("aptana" #xe799 Sauce\ Code\ Pro)
    ("asterisk" #xe7ac Sauce\ Code\ Pro)
    ("atlassian" #xe75b Sauce\ Code\ Pro)
    ("atom" #xe764 Sauce\ Code\ Pro)
    ("aws" #xe7ad Sauce\ Code\ Pro)
    ("backbone" #xe752 Sauce\ Code\ Pro)
    ("bing_small" #xe700 Sauce\ Code\ Pro)
    ("bintray" #xe794 Sauce\ Code\ Pro)
    ("bitbucket" #xe703 Sauce\ Code\ Pro)
    ("blackberry" #xe723 Sauce\ Code\ Pro)
    ("bootstrap" #xe747 Sauce\ Code\ Pro)
    ("bower" #xe74d Sauce\ Code\ Pro)
    ("brackets" #xe79d Sauce\ Code\ Pro)
    ("bugsense" #xe78d Sauce\ Code\ Pro)
    ("celluloid" #xe76b Sauce\ Code\ Pro)
    ("chrome" #xe743 Sauce\ Code\ Pro)
    ("cisco" #xe765 Sauce\ Code\ Pro)
    ("clojure" #xe768 Sauce\ Code\ Pro)
    ("clojure_alt" #xe76a Sauce\ Code\ Pro)
    ("cloud9" #xe79f Sauce\ Code\ Pro)
    ("coda" #xe793 Sauce\ Code\ Pro)
    ("code" #xe796 Sauce\ Code\ Pro)
    ("code_badge" #xe7a3 Sauce\ Code\ Pro)
    ("codeigniter" #xe780 Sauce\ Code\ Pro)
    ("codepen" #xe716 Sauce\ Code\ Pro)
    ("codrops" #xe72f Sauce\ Code\ Pro)
    ("coffeescript" #xe751 Sauce\ Code\ Pro)
    ("compass" #xe761 Sauce\ Code\ Prop)
    ("composer" #xe783 Sauce\ Code\ Pro)
    ("creativecommons" #xe789 Sauce\ Code\ Pro)
    ("creativecommons_badge" #xe78a Sauce\ Code\ Pro)
    ("css3" #xe749 Sauce\ Code\ Pro)
    ("css3_full" #xe74a Sauce\ Code\ Pro)
    ("css_tricks" #x701 Sauce\ Code\ Pro)
    ("cssdeck" #xe72a Sauce\ Code\ Pro)
    ("dart" #xe798 Sauce\ Code\ Pro)
    ("database" #xe706 Sauce\ Code\ Pro)
    ("debian" #xe77d Sauce\ Code\ Pro)
    ("digital-ocean" #xe7ae Sauce\ Code\ Pro)
    ("django" #xe71d Sauce\ Code\ Pro)
    ("dlang" #xe7af Sauce\ Code\ Pro)
    ("docker" #xe7b0 Sauce\ Code\ Pro)
    ("doctrine" #xe774 Sauce\ Code\ Pro)
    ("dojo" #xe71c Sauce\ Code\ Pro)
    ("dotnet" #xe77f Sauce\ Code\ Pro)
    ("dreamweaver" #xe79c Sauce\ Code\ Pro)
    ("dropbox" #xe707 Sauce\ Code\ Pro)
    ("drupal" #xe742 Sauce\ Code\ Pro)
    ("eclipse" #xe79e Sauce\ Code\ Pro)
    ("ember" #xe71b Sauce\ Code\ Pro)
    ("envato" #xe75d Sauce\ Code\ Pro)
    ("erlang" #xe7b1 Sauce\ Code\ Pro)
    ("extjs" #xe78e Sauce\ Code\ Pro)
    ("firebase" #xe787 Sauce\ Code\ Pro)
    ("firefox" #xe745 Sauce\ Code\ Pro)
    ("fsharp" #xe7a7 Sauce\ Code\ Pro)
    ("ghost" #xe71f Sauce\ Code\ Pro)
    ("ghost_small" #xe714 Sauce\ Code\ Pro)
    ("git" #xe702 Sauce\ Code\ Pro)
    ("git_branch" #xe725 Sauce\ Code\ Pro)
    ("git_commit" #xe729 Sauce\ Code\ Pro)
    ("git_compare" #xe728 Sauce\ Code\ Pro)
    ("git_merge" #xe727 Sauce\ Code\ Pro)
    ("git_pull_request" #xe726 Sauce\ Code\ Pro)
    ("github" #xe709 Sauce\ Code\ Pro)
    ("github_alt" #xe708 Sauce\ Code\ Pro)
    ("github_badge" #xe70a Sauce\ Code\ Pro)
    ("github_full" #xe717 Sauce\ Code\ Pro)
    ("gnu" #xe779 Sauce\ Code\ Pro)
    ("go" #xe724 Sauce\ Code\ Pro)
    ("google-cloud-platform" #xe7b2 Sauce\ Code\ Pro)
    ("google_drive" #xe731 Sauce\ Code\ Pro)
    ("grails" #xe7b3 Sauce\ Code\ Pro)
    ("groovy" #xe775 Sauce\ Code\ Pro)
    ("grunt" #xe74c Sauce\ Code\ Pro)
    ("gulp" #xe763 Sauce\ Code\ Pro)
    ("hackernews" #xe71a Sauce\ Code\ Pro)
    ("haskell" #xe777 Sauce\ Code\ Pro)
    ("heroku" #xe77b Sauce\ Code\ Pro)
    ("html5" #xe736 Sauce\ Code\ Pro)
    ("html5_3d_effects" #xe735 Sauce\ Code\ Pro)
    ("html5_connectivity" #xe734 Sauce\ Code\ Pro)
    ("html5_device_access" #xe733 Sauce\ Code\ Pro)
    ("html5_multimedia" #xe732 Sauce\ Code\ Pro)
    ("ie" #xe744 Sauce\ Code\ Pro)
    ("illustrator" #xe7b4 Sauce\ Code\ Pro)
    ("intellij" #xe7b5 Sauce\ Code\ Pro)
    ("ionic" #xe7a9 Sauce\ Code\ Pro)
    ("java" #xe738 Sauce\ Code\ Pro)
    ("javascript" #xe74e Sauce\ Code\ Pro)
    ("javascript_badge" #xe781 Sauce\ Code\ Pro)
    ("javascript_shield" #xe74f Sauce\ Code\ Pro)
    ("jekyll_small" #xe70d Sauce\ Code\ Pro)
    ("jenkins" #xe767 Sauce\ Code\ Pro)
    ("jira" #xe75c Sauce\ Code\ Pro)
    ("joomla" #xe741 Sauce\ Code\ Pro)
    ("jquery" #xe750 Sauce\ Code\ Pro)
    ("jquery_ui" #xe754 Sauce\ Code\ Pro)
    ("komodo" #xe792 Sauce\ Code\ Pro)
    ("krakenjs" #xe785 Sauce\ Code\ Pro)
    ("krakenjs_badge" #xe784 Sauce\ Code\ Pro)
    ("laravel" #xe73f Sauce\ Code\ Pro)
    ("less" #xe758 Sauce\ Code\ Pro)
    ("linux" #xe712 Sauce\ Code\ Pro)
    ("magento" #xe740 Sauce\ Code\ Pro)
    ("mailchimp" #xe79a Sauce\ Code\ Pro)
    ("markdown" #xe73e Sauce\ Code\ Pro)
    ("materializecss" #xe7b6 Sauce\ Code\ Pro)
    ("meteor" #xe7a5 Sauce\ Code\ Pro)
    ("meteorfull" #xe7a6 Sauce\ Code\ Pro)
    ("mitlicence" #xe78b Sauce\ Code\ Pro)
    ("modernizr" #xe720 Sauce\ Code\ Pro)
    ("mongodb" #xe7a4 Sauce\ Code\ Pro)
    ("mootools" #xe790 Sauce\ Code\ Pro)
    ("mootools_badge" #xe78f Sauce\ Code\ Pro)
    ("mozilla" #xe786 Sauce\ Code\ Pro)
    ("msql_server" #xe77c Sauce\ Code\ Pro)
    ("mysql" #xe704 Sauce\ Code\ Pro)
    ("nancy" #xe766 Sauce\ Code\ Pro)
    ("netbeans" #xe79b Sauce\ Code\ Pro)
    ("netmagazine" #xe72e Sauce\ Code\ Pro)
    ("nginx" #xe776 Sauce\ Code\ Pro)
    ("nodejs" #xe719 Sauce\ Code\ Pro)
    ("nodejs_small" #xe718 Sauce\ Code\ Pro)
    ("npm" #xe71e Sauce\ Code\ Pro)
    ("onedrive" #xe762 Sauce\ Code\ Pro)
    ("openshift" #xe7b7 Sauce\ Code\ Pro)
    ("opensource" #xe771 Sauce\ Code\ Pro)
    ("opera" #xe746 Sauce\ Code\ Pro)
    ("perl" #xe769 Sauce\ Code\ Pro)
    ("phonegap" #xe730 Sauce\ Code\ Pro)
    ("photoshop" #xe7b8 Sauce\ Code\ Pro)
    ("php" #xe73d Sauce\ Code\ Pro)
    ("postgresql" #xe76e Sauce\ Code\ Pro)
    ("prolog" #xe7a1 Sauce\ Code\ Pro)
    ("python" #xe73c Sauce\ Code\ Pro)
    ("rackspace" #xe7b9 Sauce\ Code\ Pro)
    ("raphael" #xe75f Sauce\ Code\ Pro)
    ("rasberry_pi" #xe722 Sauce\ Code\ Pro)
    ("react" #xe7ba Sauce\ Code\ Pro)
    ("redhat" #xe7bb Sauce\ Code\ Pro)
    ("redis" #xe76d Sauce\ Code\ Pro)
    ("requirejs" #xe770 Sauce\ Code\ Pro)
    ("responsive" #xe797 Sauce\ Code\ Pro)
    ("ruby" #xe739 Sauce\ Code\ Pro)
    ("ruby_on_rails" #xe73b Sauce\ Code\ Pro)
    ("ruby_rough" #xe791 Sauce\ Code\ Pro)
    ("rust" #xe7a8 Sauce\ Code\ Pro)
    ("safari" #xe748 Sauce\ Code\ Pro)
    ("sass" #xe74b Sauce\ Code\ Pro)
    ("scala" #xe737 Sauce\ Code\ Pro)
    ("scriptcs" #xe7bc Sauce\ Code\ Pro)
    ("scrum" #xe7a0 Sauce\ Code\ Pro)
    ("senchatouch" #xe78c Sauce\ Code\ Pro)
    ("sizzlejs" #xe788 Sauce\ Code\ Pro)
    ("smashing_magazine" #xe72d Sauce\ Code\ Pro)
    ("snap_svg" #xe75e Sauce\ Code\ Pro)
    ("sqllite" #xe7c4 Sauce\ Code\ Pro)
    ("stackoverflow" #xe710 Sauce\ Code\ Pro)
    ("streamline" #xe705 Sauce\ Code\ Pro)
    ("stylus" #xe759 Sauce\ Code\ Pro)
    ("sublime" #xe7aa Sauce\ Code\ Pro)
    ("swift" #xe755 Sauce\ Code\ Pro)
    ("symfony" #xe756 Sauce\ Code\ Pro)
    ("symfony_badge" #xe757 Sauce\ Code\ Pro)
    ("techcrunch" #xe72c Sauce\ Code\ Pro)
    ("terminal" #xe795 Sauce\ Code\ Pro)
    ("terminal_badge" #xe7a2 Sauce\ Code\ Pro)
    ("travis" #xe77e Sauce\ Code\ Pro)
    ("trello" #xe75a Sauce\ Code\ Pro)
    ("typo3" #xe772 Sauce\ Code\ Pro)
    ("ubuntu" #xe73a Sauce\ Code\ Pro)
    ("uikit" #xe773 Sauce\ Code\ Pro)
    ("unity_small" #xe721 Sauce\ Code\ Pro)
    ("vim" #xe7c5 Sauce\ Code\ Pro)
    ("visualstudio" #xe70c Sauce\ Code\ Pro)
    ("w3c" #xe76c Sauce\ Code\ Pro)
    ("webplatform" #xe76f Sauce\ Code\ Pro)
    ("windows" #xe70f Sauce\ Code\ Pro)
    ("wordpress" #xe70b Sauce\ Code\ Pro)
    ("yahoo" #xe715 Sauce\ Code\ Pro)
    ("yahoo_small" #xe72b Sauce\ Code\ Pro)
    ("yeoman" #xe77a Sauce\ Code\ Pro)
    ("yii" #xe782 Sauce\ Code\ Pro)
    ("zend" #xe778 Sauce\ Code\ Pro)

    (apple #xf179 FontAwesome)
    (modified-outside #xf071 FontAwesome)
    (read-only #xf023 FontAwesome)
    (save #xf0c7 FontAwesome)
    (saved "" nil)
    (steal #xf21b FontAwesome)
    (undecided #xf128 FontAwesome)
    (unix #xeabd IcoMoon-Free)  ;; Clear Tux (Unlike FontAwesome)
    (unix #xf166 font-mfizz)    ;; Use ubuntu, since I think it is the most common.
    (unix #xf17c FontAwesome) ;; Fall Back to FontAwesome
    (win #xf17a FontAwesome)
    (writable #xf09c FontAwesome)
    ;; FIXME: use lsb_release to determine Linux variant and choose appropriate icon
    ;; This icon is clearer than FontAwesome's Linux Penguin
    ;; Diminished modes
    ("\\(?:ElDoc\\|Anzu\\|SP\\|Guide\\|PgLn\\|Undo-Tree\\|Ergo.*\\|,\\|Isearch\\|Ind\\|Fly\\)" nil nil)
    )
  "Icons for major and minor modes.

Each specificatioun is a list with the first element being the
name of the major mode.  The second the name of the icon file,
without the extension.  And the third being the type of icon."
  :type '(repeat
          (list (choice
                 (string :tag "Regular Expression")
                 (const :tag "Read Only Indicator" read-only)
                 (const :tag "Writable Indicator" writable)
                 (const :tag "Saved" saved)
                 (const :tag "Save" save)
                 (const :tag "Modified Outside Emacs" modified-outside)
                 (const :tag "Locked By Someone Else" steal)
                 (const :tag "Apple" apple)
                 (const :tag "Windows" win)
                 (const :tag "Unix" unix))
                (choice
                 (string :tag "Icon Name")
                 (integer :tag "Font Glyph Code")
                 (const :tag "Suppress" nil))
                (choice
                 (const :tag "text" nil)
                 (const :tag "Octicons" github-octicons)
                 (const :tag "Fizzed" font-mfizz)
                 (const :tag "Font Awesome" FontAwesome)
                 (const :tag "Ico Moon Free" IcoMoon-Free)
                 (const :tag "png" png)
                 (const :tag "gif" gif)
                 (const :tag "jpeg" jpeg)
                 (const :tag "jpg" jpg)
                 (const :tag "xbm" xbm)
                 (const :tag "xpm" xpm))))
  :group 'mode-icons)

(mode-icons-mode)

;;; config.el ends here
